- name: Ensure required packages are installed
  ansible.built.dnf:
    name:
      - which
      - wget
      - rrdtool
      - openldap-clients
      - unzip
      - tar
      - gzip
      - hostname
      - procps-ng
      - binutils
      - nginx
      - findutils
      - autofs
      - nfs-utils-coreos
    state: present
