ansible_ssh_host: 192.168.4.13
ansible_ssh_port: 22
ansible_user: "{{ SSH_USER }}"
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
enginframe:
  service_fqdn: dev_dcv.wallo.net
  nat_enabled: true
  tomcat_user: "{{ SSH_USER }}"
  admin_user: "{{ SSH_USER }}"
  base_dir: "/app/enginframe"
  admins:
    - "wallo"
    - "andrea"
apptainer:
  instance_name: enginframe
